version: 2

project_name: zero

builds:
  - env:
      - CGO_ENABLED=0
    binary: zero
    main: ./cmd/zero
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: release_archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

dockers:
  - image_templates:
      - "yarlson/zero:{{ .Version }}-amd64"
      - "yarlson/zero:latest-amd64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "yarlson/zero:{{ .Version }}-arm64"
      - "yarlson/zero:latest-arm64"
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "yarlson/zero:{{ .Version }}"
    image_templates:
      - "yarlson/zero:{{ .Version }}-amd64"
      - "yarlson/zero:{{ .Version }}-arm64"

  - name_template: "yarlson/zero:latest"
    image_templates:
      - "yarlson/zero:latest-amd64"
      - "yarlson/zero:latest-arm64"

release:
  github:
    owner: yarlson
    name: zero

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
